config/routes.rb
Rails.application.routes.draw do
  root 'songs#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :update, :edit, :show] do
  end
  resources :actives, only: [:show]
  get 'login', to: 'sessions#new', as: :login
  get 'signup', to: 'users#new', as: :signup
  delete 'logout', to: 'sessions#destroy', as: :logout

  resources :songs do
    resources :comments, only: [:create, :destroy]
  end

  resource :likes, only: [:create, :destroy]

  get 'collect', to: 'songs#collect', as: :collect
  resources :user_songs
  resources :user_likes
  post 'search', to: 'search#index', as: :search
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader
  has_many :songs
  has_many :comments
  has_many :likes, foreign_key: "user_id"
  VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: true}
  validates :password, presence: true,
            confirmation: true,
            length: {in: 6..16},
            on: :create

  def to_param
    name
  end

  def liking?(likeable)
    likes.find_by(likeable)
  end

  def like!(type, id)
    likes.create!(likeable_type: type, likeable_id: id)
  end

  def unlike!(type, id)
    likes.find_by(likeable_type: type, likeable_id: id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :update]
  before_action :find_correct_user, only: [:edit, :update]
  before_action :not_login_user, only: [:new, :create]
  before_action :find_user, only: [:show]

  def show
    if @user
      @songs = @user.songs.order("created_at desc")
    else
      redirect_to root_path
      flash[:error] = "The user does not exist"
    end
  end

  def new
    @user = User.new
    @signup = true
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Regiter successfully"
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    else
      respond_to do |format|
        format.html {render 'new'}
        format.js
      end
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(update_user_params)
      flash[:success] = "Profile saved"
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    else
      flash[:error] = "Profile save fail"
      respond_to do |format|
        format.html {render 'edit'}
        format.js
      end
    end
  end

  private
  def find_correct_user
    @user = User.find_by_name(params[:id])
    unless current_user?(@user)
      flash[:warning] = "Permission Deny"
      redirect_to root_path
    end
  end

  def find_user
    @user = User.find_by_name(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def update_user_params
    params.require(:user).permit(:name, :avatar)
  end

  def not_login_user
    if logged_in?
      redirect_to root_path
      flash[:warning] = "User has already logged in"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end

  def require_login
    if !logged_in?
      redirect_to login_url
      flash[:warning] = "Login First"
    end
  end
end

app/views/users/_user_panel.html.slim
.item.header-text-right
  = link_to :logout, method: :delete, class: "item", style: 'float: right'
    i.sign.out.red.icon.logout Log out
.item.pull-right
  = link_to current_user
    = image_tag current_user.avatar_url(:large), class: "ui circular image thumb-icon user-avatar run-popup", data: { description: "Check your profile", variation: "large"}

app/views/users/create.js.erb
$('.ui.form').removeClass('loading')
<% if @user.errors.empty? %>
  Turbolinks.visit('<%= root_path %>');
<% else %>
  $('#signup-errors').html("<%= j render 'shared/error_messages', object: @user %>");
  $('#error_explanation').transition('error');
<% end %>

app/views/users/edit.html.slim
.ui.grid
  .six.wide.column
  .four.wide.column
    .ui.form
      #user-edit-errors
        = render 'shared/error_messages', object: @user
      = form_for @user, remote: true do |f|
        .ui.center.aligned.field.basic.segment
          = image_tag(current_user.avatar_url(:large), class: "ui image circular thumb user-avatar user-avatar-upload run-popup", data: { description: "#{t('.upload_avatar')}", position: "top center" })
          = f.file_field :avatar, class: "upload-avatar"
        .field
          = f.text_field :email, placeholder: "Email", disabled: "disabled"
        .field
          = f.text_field :name, placeholder: "Name"
        .ui.buttons.session-buttons
          = link_to "My Account", user_path(@user), class: "ui button orange"
          .or
          = f.submit "Save", class: "ui blue button"

app/views/users/new.html.slim
.pin-button
  img#rainyday src="#{asset_path("night.jpg")}"
  .wallpaper
    .signup-form
      #signup-errors
        = render 'shared/error_messages', object: @user
      = form_for @user, remote: true do |f|
        .ui.form
          .field
            .ui.left.icon.large.input
              = f.text_field :name, placeholder: "Name"
              i.user.icon
          .field
            .ui.left.icon.large.input
              = f.text_field :email, placeholder: "Email"
              i.mail.icon
          .field
            .ui.left.icon.large.input
              = f.password_field :password, placeholder: "Password"
              i.lock.icon
          .field
            .ui.left.icon.large.input
              = f.password_field :password_confirmation, placeholder: "Password confirmation"
              i.lock.icon
          = f.submit "Signup", class: "ui fluid green large button", data: {disable_with: "Submitting"}

app/views/users/show.html.slim
#canvas-bg
canvas#particles
.ui.grid
  .three.wide.column
  .ten.wide.column
    #user-show
      .fourteen.wide.column
        .one.wide.column
          .ui.five.wide.column.center.aligned.info-column
            = image_tag(@user.avatar_url(:large), class: "ui image circular lg  run-popup")
            .center
              h1 = @user.name
            .center
              = link_to "Click here to edit your account", edit_user_path(current_user), class: "item"
            .ui.divider
              - class_name = "ui left aligned basic segment"
              .user-status class="#{class_name}"
                .user-created-at
                  p Created at: #{time_ago_in_words(@user.created_at)} ago
                .user-songs-count
                  p Total Song: #{t('.songs_count', count: @user.songs.count)}
                .user-comments-count
                  p Total comment: #{t('.songs_count', count: @user.comments.count)}
          .nine.wide.column.content-column
            .ui.secondary.large.menu data-loading="Loading"
              = link_to "My Songs", user_songs_url, remote: true, class: "active item"
              = link_to "My Favorite Songs", user_likes_url, remote: true, class: "item"
            #songs.status-panel
              = render 'songs/play_list', songs: @songs

app/views/users/update.js.erb
<% if @user.errors.empty? %>
  Turbolinks.visit('<%= user_path(@user) %>');
<% else %>
  $('#user-edit-errors').html("<%= j render 'shared/error_messages', object: @user %>")
  $('#error_explanation').transition('error');
<% end %>