config/routes.rb
Rails.application.routes.draw do
  root 'songs#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :update, :edit, :show] do
  end
  resources :actives, only: [:show]
  get 'login', to: 'sessions#new', as: :login
  get 'signup', to: 'users#new', as: :signup
  delete 'logout', to: 'sessions#destroy', as: :logout

  resources :songs do
    resources :comments, only: [:create, :destroy]
  end

  resource :likes, only: [:create, :destroy]

  get 'collect', to: 'songs#collect', as: :collect
  resources :user_songs
  resources :user_likes
  post 'search', to: 'search#index', as: :search
end

app/models/song.rb
class Song < ActiveRecord::Base
  mount_uploader :pic, PicUploader
  mount_uploader :file, FileUploader
  belongs_to :user
  has_many :comments

  has_many :likes, as: :likeable, foreign_key: "likeable_id", dependent: :destroy
  validates :user_id, presence: true
  validates :file, presence: true
  validates :title, presence: true

  scope :hot_songs, -> {joins(:likes).group('songs.id').order('count(likes.id) desc').limit(10)}

  def self.search(search)
    if search
      where(["title like ?", "%#{search}%"])
    else
      where(["title like ?", ''])
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :require_login, only: [:new, :create, :collect, :edit, :update, :destroy]
  before_action :find_song, only: [:edit, :update, :destroy]

  def index
    @songs = Song.includes(:user).all.order("created_at desc").page params[:page]
    @hot_songs = Song.hot_songs
    @user_panel = true
  end

  def new
    @song = current_user.songs.build
  end

  def show
    @hot_songs = Song.hot_songs
    @song = Song.find(params[:id])
    @comments = @song.comments.page(params[:page]).per(25)
  end

  def create
    @song = current_user.songs.build(song_params)
    if @song.save
      flash[:success] = "Publish success"
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    else
      flash[:error] = "Publish fail"
      respond_to do |format|
        format.html {render 'new'}
        format.js
      end
    end
  end

  def edit
  end

  def update
    if @song.update_attributes song_params
      flash[:success] = "Successfully updated"
      respond_to do |format|
        format.html {redirect_to @song}
        format.js
      end
    else
      respond_to do |format|
        format.html {render 'edit'}
        format.js
      end
    end
  end

  def destroy
    @song = current_user.songs.find(params[:id])
    if @song.destroy
      flash[:success] = "Song was successfully deleted"
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    end
  end

  private

  def song_params
    params.require(:song).permit(:title, :file, :singer, :artist, :pic, :description)
  end

  def find_song
    @song = current_user.songs.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:warning] = "Permission denied"
    redirect_to root_path
  end
end

app/views/songs/_form.html.slim
= form_for song, remote: true do |f|
  .ui.form
    .fields
      span.pull-mid.help-inline Upload Song
      - if action_name == "edit"
        = f.text_field :file, placeholder: "File", disabled: "disabled"
      - else
        = f.file_field :file, class: "upload-song"
    .field
      span.pull-mid.help-inline Title
      = f.text_field :title, placeholder: "Name"
    .field
      span.pull-mid.help-inline Singer
      = f.text_field :singer, placeholder: "Singer"
    .field
      span.pull-mid.help-inline Author
      = f.text_field :artist, placeholder: "Author"
    .field
      span.pull-mid.help-inline Description
      = f.text_area :description, placeholder: "Description"
    .field
      span.pull-mid.help-inline Picture
      = f.file_field :pic, class: "upload-pic"
    = f.submit "Submit", class: "ui submit button orange right floated", data: {disable_with: "Submit"}
    span.pull-right.help-inline

app/views/songs/_hot_song.html.slim
.aa-video-list
  a.aa-wishlist-video_image
    img src="#{hot_song.pic}" /
    .aa-wishlist-video_content
      .aa-soundTitle
        button.play.play-music type="button" data-file="#{hot_song.file}" data-title="#{hot_song.title}"
        .info-user
          p.aa-name-usser
            a href="#"  #{hot_song.artist}
          p.title-comment
            i.orange.sound.icon
              = link_to hot_song.title.html_safe, hot_song
      .social-link
        .com-count
          - author = song_url(hot_song) + "#comments"
          = link_to author do
            i.green.comment.icon
            = hot_song.comments.size
        .like-count
          i.red.heart.icon
            = hot_song.likes.size

app/views/songs/_play_list.html.slim
- if songs.any?
  - for song in songs
    = render 'songs/song', song: song

app/views/songs/_share_buttons.html.slim
p.share-button
  a href="https://twitter.com/intent/tweet?url=#{song_url(song)}&text=#{song.title}&via=Ting"  target="_blank"
    i.twitter.blue.icon
  a href="http://www.facebook.com/share.php?url=#{song_url(song)}"  target="_blank"
    i.facebook.purple.icon

app/views/songs/_song.html.slim
.aa-video-list id="song-#{song.id}"
  a.aa-wishlist-video_image
    img src="#{song.pic}" /
    .aa-wishlist-video_content
      .aa-soundTitle
        button.play.play-music type="button" data-file="#{song.file}" data-title="#{song.title}"
        .info-user
          p.aa-name-usser
            a href="#"  #{song.artist}
          p.title-comment
            i.orange.sound.icon
              = link_to song.title.html_safe, song
        - if current_user == song.user
          = link_to edit_song_path(song), class: "edit-song" do
            i.green.pencil.icon
          = link_to song_path(song), data: {method: "delete", confirm: "Are you sure", remote: true} do
            i.red.trash.icon
      .social-link
        .musician
          = image_tag(song.user.avatar_url(:thumb), class: "ui avatar image")
          = link_to song.user.name, song.user
        .com-count
          - author = song_url(song) + "#comments"
          = link_to author do
            i.green.comment.icon
            = song.comments.size
        .like-count
          i.red.heart.icon
            = song.likes.size

app/views/songs/_songs.html.slim
- unless @songs.blank?
  #songs data-image="#{asset_path("loading.gif")}" class='aa-wishlist-video'
    .title-left
      span.number.fa.fa-heart New Songs
    - for song in @songs
      = render 'songs/song', song: song
    #pagination data-loaded="All songs are loaded"
      = paginate @songs
- else
  #songs data-image="#{asset_path("loading.gif")}" class='aa-wishlist-video'
    .title-left
      span.number.fa.fa-heart No Song Found
.left-video
  .title-left
    span.number.fa.fa-heart Hot Songs
  ul.list
  - for hot_song in @hot_songs
    = render 'songs/hot_song', hot_song: hot_song

app/views/songs/create.js.erb
<% if @song.errors.empty? %>
new_song = "<%= j render 'song', song: @song %>";
$('#songs').append(new_song);
$('#flash-errors').html("<%= j render 'shared/flash', object: @song %>");
animated();
<% else %>
$('#flash-errors').html("<%= j render 'shared/flash', object: @song %>");
$('#error_explanation').transition('error');
$('.close.red').click();
<% end %>
$('.ui.form').removeClass('loading');
$('.play-music').remove('click');
$('.play-music').click(function() {
    music_player.jPlayer("setMedia", {
        title: $(this).attr('data-title'),
        mp3: $(this).attr('data-file')
    });
    music_player.jPlayer("play", 1);
});

function animated() {
    $('#error_explanation').html("");
    $('#song-<%= @song.id %>').addClass('animated flipInX');
    $('.close.red').click();
}

app/views/songs/destroy.js.erb
$(function(){
    $('#song-<%= @song.id %>').addClass('animated flipOutX')
                                                  .one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', 
        function(){
            $('#song-<%= @song.id %>').remove();
        }
    );
});

app/views/songs/edit.html.slim
.ui.grid
  .four.wide.column
  #song-edit.eight.wide.column
    = render 'form', song: @song

app/views/songs/index.html.slim
= render 'songs', index: true

app/views/songs/new.html.slim
.ui.grid
  .five.wide.column
  .six.wide.column
    = render 'form', song: @song

app/views/songs/show.html.slim
- id = @song.id
- user = @song.user
.ui.grid
  .four.wide.column
  .eight.wide.column
    .ui.one.column.grid.songs-list id="song-#{@song.id}"
      .sixteen.wide.column.song-info

        .song-container.ui.grid
          .ui.five.wide.column
            .album-pic
              .outer-pic.ui.circular.image.dimmer-image
                img src="#{@song.pic}"
              button.play.play-music type="button" data-file="#{@song.file}" data-title="#{@song.title}"
          .ui.eleven.wide.column
            .song-panel
              h3.header
                i.orange.sound.icon
                = link_to @song.title.html_safe, @song
              p
                i.green.icon
                a = ' Singer: ' + @song.singer
              p
                i.user.green.icon
                a = ' Author: ' + @song.artist
              p.song-toolbar
                = link_to user
                  = image_tag(@song.user.avatar_url(:small), class: "ui mini-avatar avatar image run-popup", data: { content: "#{user.name}", position: "bottom center" } )
                span.song-tools-divider •

                i.teal.calendar.icon
                  = ' ' + @song.created_at.strftime("%F")
                span.song-tools-divider •
                span.item id="like-song-#{@song.id}"
                  - @likeable = {likeable_type: 'Song', likeable_id: @song.id}
                  = likeable_likes_tag @likeable
                span.song-tools-divider
                - if current_user == user
                  span.song-tools-divider •
                  = link_to edit_song_path(@song) do
                    i.green.icon.pencil
                  span.song-tools-divider •

                  = link_to song_path(@song), method: :delete, data: { confirm: "Are you sure" }
                    i.red.icon.trash
              = render 'share_buttons', song: @song
          .ui.sixteen.wide.column
            h2 Description:
            .song-content
              = @song.description
        .song-footer

    .ui.horizontal.icon.divider
      i.circular.red.chat.icon

    #comments
      .column
        .ui.comments
          - if @comments.any?
            = render @comments
          - else
            .ui.center.aligned.basic.segment = "No comment found"

        = paginate @comments

        .ui.horizontal.icon.divider
          i.circular.green.pencil.icon
        - if logged_in?
          = render 'comments/form'
        - else
          .ui.center.aligned.basic.segment
            = link_to :login
              .ui.animated.fade.blue.button
                .visible.content = "Login first"
                .hidden.content = "Login"

app/views/songs/update.js.erb
<% if @song.errors.empty? %>
  Turbolinks.visit('<%= song_path(@song) %>')
<% else %>
  $('#song-errors').html("<%= j render 'shared/error_messages', object: @song %>");
  $('#error_explanation').transition('error');
<% end %>